blackfin: smp: fix compile error
Fix compile error, in function ‘__cmpxchg’:
/home/bob/linux-kernel-git/linux-kernel/arch/blackfin/include/asm/cmpxchg.h:66:
error: implicit declaration of function ‘smp_mb’
make[1]: *** [arch/blackfin/mach-bf561/boards/ezkit.o] Error 1
make: *** [arch/blackfin/mach-bf561/boards] Error 2

The reason is system.h has been disintegrated, smp_mb() is defined in
asm/barrier.h now.

Signed-off-by: Bob Liu <lliubbo@gmail.com>