[!no_src_qa!] Task[#2314] Bug [#1233] - commit patch which was sent upstream, no functional changes
ERROR: do not use assignment in if condition
#19: FILE: mm/nommu.c:113:
+       if (!objp || (unsigned long)objp >= memory_end || !((page = virt_to_page(objp))))

left it this way since org source was the same.



git-svn-id: svn://localhost/svn/linux-kernel/trunk@4662 526b6c2d-f592-4532-a319-5dd88ccb003d