[media] media/radio/wl1273: fix build errors
From: Randy Dunlap <randy.dunlap@oracle.com>

RADIO_WL1273 needs to make sure that the mfd core is built to avoid
build errors:

ERROR: "mfd_add_devices" [drivers/mfd/wl1273-core.ko] undefined!
ERROR: "mfd_remove_devices" [drivers/mfd/wl1273-core.ko] undefined!


git-svn-id: svn://localhost/svn/linux-kernel/trunk@9809 526b6c2d-f592-4532-a319-5dd88ccb003d