drivers: net: stmmac: fix build error after update to 3.3
drivers/net/ethernet/stmicro/stmmac/stmmac_main.c: In function
‘stmmac_hwtstamp_init’:
drivers/net/ethernet/stmicro/stmmac/stmmac_main.c:354: warning: passing
argument 2 of ‘__raw_writel’ makes pointer from integer without a cast
drivers/net/ethernet/stmicro/stmmac/stmmac_main.c: In function
‘stmmac_hw_init’:
drivers/net/ethernet/stmicro/stmmac/stmmac_main.c:2029: error: ‘dev’
undeclared (first use in this function)

Signed-off-by: Bob Liu <lliubbo@gmail.com>