Change anomaly workarounds, to be what the anomaly sheet writer ment, not what is actually said in the workarounds...
[!no_src_qa!] - due to assembly syntax in h file:

ERROR: Macros with multiple statements should be enclosed in a do -
while loop
#63: FILE: arch/blackfin/include/asm/blackfin.h:65:
+#define SSYNC(scratch) cli scratch; nop; nop; nop; SSYNC; sti scratch;



git-svn-id: svn://localhost/svn/linux-kernel/trunk@8664 526b6c2d-f592-4532-a319-5dd88ccb003d